import type { Metadata } from "next";
// auth
import { auth } from "@serverAuth";
import SessionProvider from "@components/SessionProvider/SessionProvider";
// react-query
import QueryProvider from "@react-query/QueryClient";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
// font
import { Inter } from "next/font/google";
// components
import NavBar from "@components/navBar/navBar";
import Footer from "@components/footer/footer";
import { Toaster } from "react-hot-toast";
// styles
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <QueryProvider>
            {/* <ReactQueryDevtools initialIsOpen={false} /> */}
            <NavBar />
            <Toaster />
            {children}
            <Footer />
          </QueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
